const data = [
    {"id": 0,
    "pelicula": "https://www.themoviedb.org/t/p/original/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    "nombre": "Barbie",
    "rating": "4.7 ratings",
    "synopsis": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    "banner": "https://www.themoviedb.org/t/p/w1000_and_h563_face/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
    "edad": "+13",
    },
    
    {"id": 1,
    "pelicula": "https://www.themoviedb.org/t/p/original/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 2,
    "pelicula": "https://www.themoviedb.org/t/p/original/rW0z68BytYuL88sSm8jXFExhlX7.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 3,
    "pelicula": "https://www.themoviedb.org/t/p/original/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 4,
    "pelicula": "https://www.themoviedb.org/t/p/original/yprv5PbnEksoVj2v6XEnDBg9joR.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 5,
    "pelicula": "https://lumiere-a.akamaihd.net/v1/images/p_monstersinc_19751_55afa07a.jpeg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 6,
    "pelicula": "https://static.wikia.nocookie.net/doblaje/images/7/7c/La_princesa_y_el_sapo_-_payoff.jpg/revision/latest?cb=20181111214803&path-prefix=es",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 7,
    "pelicula": "https://images.cdn3.buscalibre.com/fit-in/360x360/dc/b4/dcb426a6a4ce3afdfb3f1a8afcd4f3ae.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 8,
    "pelicula": "https://m.media-amazon.com/images/M/MV5BNmEyOWU2NjctMzY0Zi00NzBkLTg3YzAtNDI3MGE4ZTkyZTQ0XkEyXkFqcGdeQXVyMzQyMDgzOTU@._V1_.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 9,
    "pelicula": "https://pics.filmaffinity.com/Dune-209834814-large.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 10,
    "pelicula": "https://www.themoviedb.org/t/p/original/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 11,
    "pelicula": "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 12,
    "pelicula": "https://www.themoviedb.org/t/p/original/hr8ZtwdbtjBquxlTCrczr685K5T.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 13,
    "pelicula": "https://www.themoviedb.org/t/p/original/d1qDrtlRP3adVFhGlGiLLMutmRd.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 14,
    "pelicula": "https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/DP_6864887_TC_800x1200_DP_6864876_AManCalledOtto_2000x3000_EST.jpg?itok=8IeV-c2J",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
    {"id": 15,
    "pelicula": "https://pics.filmaffinity.com/One_Piece_Serie_de_TV-985097858-large.jpg",
    "nombre": "",
    "rating": "",
    "synopsis": "",
    "banner": "",
    "edad": "",
    },
]
